### ISSUE TITLE
一个关于"渲染"的问题

### ISSUE THREAD

**Issue by Mirrorgo** [Rain120/athena#2]
https://rain120.github.io/athena/zh/slate/concepts/08-rendering.html#%E5%8F%B6%E5%AD%90%E8%8A%82%E7%82%B9-leaves
👆有提到类似`<em>t<strong>e</em>x</strong>t`的情况,请问通常是如何处理成`<em>t</em><strong><em>e</em>x</strong>t`的样式的

**Comment by Rain120** [comment]
感谢关注，我个人的理解是不会出现的这种情况的，因为slate会检查节点是否合理
