### ISSUE TITLE
我翻译了slate文档的transforms部分

### ISSUE THREAD

**Issue by Mirrorgo** [Rain120/athena#3]
我发现slate文档的transforms部分没有翻译
https://docs.slatejs.org/concepts/04-transforms

我目前翻译了一份草稿在下面
https://www.yuque.com/lalala-wm82o/qvhwgq/udfwlz
如果大致可以的话我今天争取完善 (再修改一些用词和格式) 后提交一个初稿的pr🥳

**Comment by Mirrorgo** [comment]
弄好了, 麻烦看一下
https://github.com/Rain120/athena/pull/4/commits/3f89a99f0688c5849f4acd60ddfc1967c6dc3fef?short_path=e1ff387#diff-e1ff3871d7b5f36100f09059f97aad3b953f4b39dfdbb64938549c9cff5eb63f

**Comment by Mirrorgo** [comment]
是最近很忙吗, 如果有空能不能帮忙看一下我弄的翻译, 哪里不太行的话我再改改, 辛苦了

**Comment by Rain120** [comment]
- 最近刚换工作，有点忙，暂时没估计到这边的文档项目。
- 不是缺失了文档，而是Slate官方更新了，没有同步到文档
- 欢迎更新新版的Slate文档
